spring:
  application:
    name: cards-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        event:
          merge:
            entity_copy_observer: allow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:dmhdatabase}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345678}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: cards-service
    description: microservicio de administracion y registro de tarjetas de credito y debito (remoto)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8085/actuator/info
    healthCheckUrlPath: http://localhost:8085/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
