spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        event:
          merge:
            entity_copy_observer: allow
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:dmhdatabase}?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:12345678}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${dh.keycloak.clientId}
            client-secret: ${dh.keycloak.clientSecret}
            scope: openid
            realm: ${dh.keycloak.realm}
            serverUrl: ${dh.keycloak.serverUrl}
        provider:
          keycloak:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
        resourceserver:
          jwt:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
            jwk-set-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/certs

dh:
  keycloak:
    realm: dh-money-users
    serverUrl: http://localhost:8080
    clientId: api-dh-money
    clientSecret: eZ7LtbIyw308tEuJp5iBOyhuZtyB58B2
    tokenEndpoint: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/token
    
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: users-service
    description: microservicio de registro y logueo (desde config server)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8081/actuator/info
    healthCheckUrlPath: http://localhost:8081/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
